dist: trusty
sudo: false
language: ruby
rvm:
- 2.4.1
cache:
  yarn: true
  directories:
  - node_modules
before_script:
- bundle exec rake db:create:all
- bundle exec rake db:migrate
script:
- bundle exec rspec
- bundle exec cucumber
env:
  global:
    secure: WN8evaRzUqYxIMnITcrLvO8m/f48I3ow9HxbwRqbN0smWD/XfFJRSeQlJIrOZIQX6s7QKENqXNxA3a0MyOJCFonhevX8IQDQ5twqgbe9S4n2TC78j678sJ6C1WwWimLL0kjlH5KrxaIjXkKnZKAs5gaBTW0sbOKda4rXD/oPercz1Orqlt0vt8udgSpTVST3dajT8DcTBIsq0Vmsnd+a4WjG5/5yLzuFPMb5T9PgdeCs75UMvlW3LRMIQgvhdeb5xZBe5+pXRznOGI92c5/mpmSskywY5/mGLCC6RBMFVX/lCC7YcCNpGOyTjGirBh5DWKcM4fTzVyrToFj+JJlYHMJ8049HEISlWc3wd1Z79IKv1oQz0BmGPJE+TxJi1WT5hRM8eV6wjoxb4AhmeKxMh2og0gupBuJnZ6leEXN/fCE0+mmsiAH8BtiXmMjtcSkM9WBGuRBK/lXkJjh9V12r2d79Nh59su4rWDFdY/Tzuift3F9hrPn/aNkVSlxgnggf8AzsCsp3ZT5Ce7pJhdyG3dHaLZ268nvpm2znWy6sExY7ew/tE3VgXoATfbSjf8fX/vevtFIznWkrP9xn4OWxaQ0rukOFlyFb1+whRbJi9Ti5h+mxXjaLFQB2+Bs8TAfye1P4ZY665onLjld4klE9skd9etswFs2zE/ZO2FcGFnE=
