dist: trusty
sudo: false
language: ruby
rvm:
  - 2.4.1
cache:
  yarn: true
  directories:
  - node_modules
before_script:
  - bundle exec rake db:create:all
  - bundle exec rake db:migrate
script:
  - bundle exec rspec
  - bundle exec cucumber
env:
  global:
    - PAPERCLIP_HASH_SECRET=abcasdfasdfasdf235423542354asdefasdfasdf
