dist: trusty
sudo: false
language: ruby
before_script:
- npm install yarn
- yarn install
- bundle exec rake db:create:all
- bundle exec rake db:migrate
script:
- bundle exec rspec
- bundle exec cucumber
env:
  PAPERCLIP_HASH_SECRET: $PAPERCLIP_HASH_SECRET
