dist: trusty
sudo: false
language: ruby
rvm:
- 2.4.1
cache:
  yarn: true
  directories:
  - node_modules
before_script:
- bundle exec rake db:create:all
- bundle exec rake db:migrate
script:
- bundle exec rspec
- bundle exec cucumber
env:
  matrix:
    secure: iZKo8z+BiO75W0S3fKh/vgrrYSYwq9wy4amAgsqr8DQz0pTvUjM9yIjomGNPymp3B8brlezWK5RbG97xZ4dIBkZk+Hdo4GjIQaAyPn6ct6SYTvT8WQxDgD9jVlPWV8Hc+88Py5QVrUHSv01KAl69/gZGYNhu/JbshaCPVV4oELxykG4BI0ktn1gne3YhZ/CP6U1oYtPj1GQJER5123e9nrB5W7vQRMSITDlxmsp11HeC+zcZWlvOkQOW6wNwam6uJM4tF9AaZkpqSxnaSNj7+HjM4O/3zrIxgnifLNyj5a+LpnW2+qFbUowZDo15fYkfIuGHiGaDOAQ3GTjAQPx/s9R1W/IVFx+JbYdtud/Ai0T5esjce5IZxia3IzxPRjOffsPH+NfnnBYSrFrfGr/HIo3mNpDI8orGbDPKebfCZHV0XeVJORWEPGRb2Pw7GOnx5ijTpi6xF4bwSgVdKW/RLgTi9grqKVVQy9VQ4pMHB31xFois55jWc38Execs3vi3hJ60UliXCy5jU8PWx2nntHRu3Yg8BR82HEWjrXCS/CG7jQKYvQxevLZkpzF3qLDmQAomOH40L2f+2ivGvCL1n1BJDVf0WhChhHkai7LXr2kDZoKHZxKrLPxJ24areTzxWipg5FfX0JmqrX3Nj8TaWb7u5DtRSivB/ojVMykZypg=
