sudo: required
language: ruby
services:
  - docker

before_script:
- bundle install
- yarn install
- bundle exec rake db:create:all
- bundle exec rake db:migrate
script:
- bundle exec rspec
- bundle exec cucumber
env:
  PAPERCLIP_HASH_SECRET: $PAPERCLIP_HASH_SECRET
  SECRET_KEY_BASE: $SECRET_KEY_BASE
  DEVELOPMENT_KEY_BASE: $DEVELOPMENT_KEY_BASE
  ENABLE_EMAIL_CONFIRMATIONS: $ENABLE_EMAIL_CONFIRMATIONS
  NEW_TEAM_ON_SIGNUP: $NEW_TEAM_ON_SIGNUP
  ENABLE_RECAPTCHA: $ENABLE_RECAPTCHA
  ENABLE_TUTORIAL: $ENABLE_TUTORIAL
  MAIL_FROM: $MAIL_FROM
  MAIL_REPLYTO: $MAIL_REPLYTO
  MAIL_SERVER_URL: $MAIL_SERVER_URL
  MAILER_PORT: $MAILER_PORT
  PAPERCLIP_STORAGE: $PAPERCLIP_STORAGE
  SMTP_ADDRESS: $SMTP_ADDRESS
  SMTP_DOMAIN: $SMTP_DOMAIN
  SMTP_PASSWORD: $SMTP_PASSWORD
  SMTP_USERNAME: $SMTP_USERNAME
  TEST_KEY_BASE: $TEST_KEY_BASE
  WOPI_ENABLED: $WOPI_ENABLED
