dist: trusty
sudo: false
language: ruby
before_script:
- npm install yarn
- yarn install
- bundle exec rake db:create:all
- bundle exec rake db:migrate
script:
- bundle exec rspec
- bundle exec cucumber
env:
  PAPERCLIP_HASH_SECRET: $PAPERCLIP_HASH_SECRET
  SECRET_KEY_BASE: $SECRET_KEY_BASE
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_REGION: $AWS_REGION
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  DEVELOPMENT_KEY_BASE: $DEVELOPMENT_KEY_BASE
  ENABLE_RECAPTCHA: $ENABLE_RECAPTCHA
  ENABLE_TUTORIAL: $ENABLE_TUTORIAL
  MAIL_FROM: $MAIL_FROM
  MAIL_REPLYTO: $MAIL_REPLYTO
  MAIL_SERVER_URL: $MAIL_SERVER_URL
  MAILER_PORT: $MAILER_PORT
  PAPERCLIP_STORAGE: $PAPERCLIP_STORAGE
  S3_BUCKET: $S3_BUCKET
  S3_HOST_NAME: $S3_HOST_NAME
  SMTP_ADDRESS: $SMTP_ADDRESS
  SMTP_DOMAIN: $SMTP_DOMAIN
  SMTP_PASSWORD: $SMTP_PASSWORD
  SMTP_USERNAME: $SMTP_USERNAME
  TEST_KEY_BASE: $TEST_KEY_BASE
